/*
 * This source file was generated by the Gradle 'init' task
 */
package demo;
import good_night.GoodNight;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    
    public String getGoodnight() {
        GoodNight gn = new GoodNight();
	gn.main();
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
	new App().getGoodnight();;
    }
}
