/*
 * This source file was generated by the Gradle 'init' task
 */
package good_night;

public class GoodNight {
    public String getGreeting() {
        return "Good Night";
    }

    public static void main(String[] args) {
        System.out.println(new GoodNight().getGreeting());
    }
}
